-- MySQL Script generated by MySQL Workbench
-- 10/04/16 14:55:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airbnb` ;

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `Hosts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hosts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Hosts` (
  `host_ID` INT NOT NULL AUTO_INCREMENT,
  `user_ID` INT NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'fk',
  PRIMARY KEY (`host_ID`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `host_ID_UNIQUE` ON `Hosts` (`host_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_ID_UNIQUE` ON `Hosts` (`user_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Place` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Place` (
  `place_ID` INT NOT NULL AUTO_INCREMENT,
  `host_ID` INT NOT NULL,
  `addr_ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `cost_per_night` VARCHAR(45) NULL,
  `max_people` VARCHAR(45) NULL,
  `pictures` VARCHAR(45) NULL,
  `Placecol` VARCHAR(45) NULL,
  PRIMARY KEY (`place_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `place_ID_UNIQUE` ON `Place` (`place_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `host_ID_UNIQUE` ON `Place` (`host_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `addr_ID_UNIQUE` ON `Place` (`addr_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Address` (
  `addr_ID` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `place_ID` INT NULL,
  PRIMARY KEY (`addr_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `addr_ID_UNIQUE` ON `Address` (`addr_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Users` (
  `user_ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) GENERATED ALWAYS AS (concat(Fname, Lname);) VIRTUAL,
  `email` VARCHAR(45) NOT NULL,
  `addr_ID` INT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `DOB` VARCHAR(45) NOT NULL,
  `profile_pic` VARCHAR(45) NULL,
  `bio` VARCHAR(45) NULL,
  `join_date` VARCHAR(45) NULL,
  `payOptions_ID` INT NULL,
  PRIMARY KEY (`user_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_ID_UNIQUE` ON `Users` (`user_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Client` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Client` (
  `client_ID` INT NOT NULL,
  `user_ID` INT NOT NULL,
  PRIMARY KEY (`client_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `client_ID_UNIQUE` ON `Client` (`client_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_ID_UNIQUE` ON `Client` (`user_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Request` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Request` (
  `req_ID` INT NOT NULL AUTO_INCREMENT,
  `client_ID` INT NOT NULL,
  `place_ID` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `date_req` VARCHAR(45) NULL,
  `date_range` VARCHAR(45) NULL,
  `date_resp` VARCHAR(45) NULL,
  PRIMARY KEY (`req_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `req_ID_UNIQUE` ON `Request` (`req_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reservation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Reservation` (
  `reservation_ID` INT NOT NULL,
  `place_ID` INT NOT NULL,
  `host_ID` INT NOT NULL,
  `client_ID` INT NOT NULL,
  `processPay_ID` INT NOT NULL,
  `date_range` VARCHAR(45) NULL,
  PRIMARY KEY (`reservation_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
